### ISSUE TITLE
[Bug] Shape Editor doesn't accept coordinates over 10,000,000

### ISSUE THREAD

**Issue by Blakepane** [maruohon/minihud#341]
Trying to input or use "Set Here" for a coordinate larger than +/-10,000,000 doesn't get accepted. Very niche scenario, but renders the Shape Manager useless if beyond 10,000,000.

minihud-fabric-1.20.4-0.30.2

**Comment by maruohon** [comment]
Which shape are you referring to?

The shapes have some limits for their maximum size, and I think at least some of them still tie the edit menu controls too directly to the actual shape values. Which means that if you for example need to set two corner points, it might reject the first one if it moves too much from the old values, before you even have the chance to set the other corner.

I think I fixed this recently for the Box shape for the 0.30.1 version, although I don't remember anymore how I did it and if it still would have this particular issue. Before it even had issues setting the corners at all even in small distances, depending on which corner you tried to move first or which one was on the negative side...

**Comment by Blakepane** [comment]
I was mainly using Circle / Cylinder for testing, but I also tried different shapes too. I'm not sure if I changed something, though, because now the rendering is working as expected. 

Regardless, the coordinate still doesn't show up in the box and is left blank despite rendering at the correct position.
