### ISSUE TITLE
Server TPS Information breaks when PlaceholderAPI plugin is active

### ISSUE THREAD

**Issue by JonA02** [maruohon/minihud#43]
When I login to my server with the Placeholder API plugin active, the Server TPS information in the HUD breaks. It just constantly flashes saying "no valid data". The TPS information works fine when I'm on a server without the plugin, and when I'm in singleplayer. 

<img width="340" alt="Screen Shot 2020-04-14 at 10 40 14 pm" src="https://user-images.githubusercontent.com/35551235/79226015-02cc4f80-7ea1-11ea-9b04-76c541dd6410.png">

**Comment by maruohon** [comment]
The TPS information on a server isn't super accurate anyway unless the server actually sends the data to the client, which currently only happens (at least in a format that MiniHUD knows about) on servers that are running either the carpet mod, or the MUP bugfix mod. In other cases it's just a client-side estimate based on the interval of the received time sync packets, which normally arrive every 20 ticks. So in such cases it can only show meaningful MSPT values if the MSPT goes above the normal 50 ms/tick.

However I'm rather curious why that plugin would break this... Also I don't remember of the top of my head what the condition is for clearing the data and showing the "no valid data" message. I think I fixed a bug related to this a while back, but I don't remember which MC versions the fix is in currently, it might still only be in the 1.12 versions. And now I actually remembered what the issue was. Does that plugin send something in the player list footer? Because previously if MiniHUD saw something there that wasn't the TPS / MSPT data it expected from Carpet mod, it would clear the data and thus show/flash the no valid data message.

**Comment by JonA02** [comment]
Yeah so right now, I'm using the TAB plugin and the Placeholder API plugin on the server. The Placeholder plugin is sending data to the TAB plugin - like server uptime - to the player list footer. You think there's any way around it? Would installing carpet mod fix it?

**Comment by maruohon** [comment]
The fix needs to be in MiniHUD, and also you can't install Carpet mod at the same time if you are running Spigot/Paper/whatever for plugins.

I think the 1.16 snapshot builds of MiniHUD probably should have that fix as I did a temporary port of the 1.12 code to those builds. You can use the `20w09a` build of MiniHUD also on MC 1.15.x (assuming that's what you are using, as you didn't mention it anywhere). It can be found here: https://masa.dy.fi/mcmods/client_mods/?mcver=1.16-snapshot-20w09a

**Comment by JonA02** [comment]
Oh yeah sorry forgot to mention that. I am using 1.15.2. I tried the 20w09a version and it didn't fix it. You think the other snapshot versions would fix it? I don't mind trying all of them.

**Comment by maruohon** [comment]
No they are feature-wise equivalent, but any newer versions won't run on 1.15.x anymore due to vanilla changes.

**Comment by JonA02** [comment]
Oh no worries. If there's no work around currently, I'll just wait for the 1.16 updates to roll out. They're not too far off anyways.
Thanks for you help though. Muchly appreciated.
